QUIZZES = {
    '10000001': {
        "access_code": None,
        "all_dates": [
            {
                "base": True,
                "due_at": None,
                "lock_at": None,
                "unlock_at": None
            }
        ],
        "allowed_attempts": 1,
        "assignment_group_id": None,
        "assignment_id": None,
        "can_unpublish": True,
        "can_update": True,
        "cant_go_back": False,
        "description": "<link rel=\"stylesheet\" href=\"https://instructure-uploads.s3.amazonaws.com/account_92700000000000001/attachments/8318941/dp_app.css\"><p></p><div class=\"qg-root-block qg-block\"><p style=\"margin-top: 0\">This quiz is open note, open book, and open world. Assume all regular expressions are done in Python using the <code style=\"margin-left: 0.25em; margin-right: 0.25em\">re</code> standard library. Good luck!</p></div><p></p><br><hr><p>Version: 23ba44bf</p><script src=\"https://instructure-uploads.s3.amazonaws.com/account_92700000000000001/attachments/8318940/dp_app.js\"></script>",
        "due_at": None,
        "has_access_code": False,
        "hide_correct_answers_at": None,
        "hide_results": None,
        "html_url": "https://canvas.ucsc.edu/courses/12345/quizzes/10000001",
        "id": "10000001",
        "important_dates": False,
        "in_paced_course": False,
        "ip_filter": None,
        "lock_at": None,
        "lock_explanation": "This quiz is currently locked.",
        "lock_info": {
            "asset_string": "quizzes:quiz_10000001",
            "missing_permission": "participate_as_student"
        },
        "lockdown_browser_monitor_data": None,
        "locked_for_user": True,
        "message_students_url": "https://canvas.ucsc.edu/api/v1/courses/12345/quizzes/10000001/submission_users/message",
        "migration_id": None,
        "mobile_url": "https://canvas.ucsc.edu/courses/12345/quizzes/10000001?force_user=1&persist_headless=1",
        "one_question_at_a_time": False,
        "one_time_results": False,
        "only_visible_to_overrides": False,
        "permissions": {
            "create": True,
            "delete": True,
            "grade": True,
            "manage": True,
            "manage_assign_to": True,
            "preview": True,
            "read": True,
            "read_statistics": True,
            "review_grades": True,
            "submit": True,
            "update": True,
            "view_answer_audits": False
        },
        "points_possible": 0.0,
        "post_to_sis": None,
        "published": False,
        "question_count": 2,
        "quiz_reports_url": "https://canvas.ucsc.edu/api/v1/courses/12345/quizzes/10000001/reports",
        "quiz_statistics_url": "https://canvas.ucsc.edu/api/v1/courses/12345/quizzes/10000001/statistics",
        "quiz_submission_versions_html_url": "https://canvas.ucsc.edu/courses/12345/quizzes/10000001/submission_versions",
        "quiz_type": "practice_quiz",
        "require_lockdown_browser": False,
        "require_lockdown_browser_for_results": False,
        "require_lockdown_browser_monitor": False,
        "scoring_policy": "keep_highest",
        "section_count": 1,
        "show_correct_answers": True,
        "show_correct_answers_at": None,
        "show_correct_answers_last_attempt": False,
        "shuffle_answers": True,
        "speed_grader_url": None,
        "time_limit": 30,
        "timer_autosubmit_disabled": False,
        "title": "Regular Expressions",
        "unlock_at": None,
        "unpublishable": True,
        "version_number": 2,
        "visible_to_everyone": True
    }
}
